import fetch from "node-fetch";

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const inputs = req.body || {};

    // 🧠 Build the prompt
    const systemPrompt = `
You are Pool ChemGPT, a professional pool-water technician.
Analyse the pool readings below and generate a clear treatment report.

${JSON.stringify(inputs, null, 2)}

Respond in markdown with:
- Heading: "Pool Water Treatment Report"
- Sections: Analysis, Chemical Adjustments (dosages in g / mL based on pool_volume), Step-by-Step Actions, Maintenance Checklist.
- Keep tone professional and concise.
`;

    // 🧱 Use project-specific API endpoint
    const apiUrl = `https://api.openai.com/v1/chat/completions?project=${process.env.OPENAI_PROJECT_ID}`;

    // 🧾 Send request to OpenAI
    const openaiRes = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: "Generate a pool chemical treatment report." },
        ],
        max_tokens: 800,
        temperature: 0.7,
      }),
    });

    const data = await openaiRes.json();
    console.log("🔍 OpenAI response:", JSON.stringify(data, null, 2));

    if (openaiRes.status !== 200) {
      return res
        .status(openaiRes.status)
        .json({ error: data.error?.message || "OpenAI API error" });
    }

    const report =
      data?.choices?.[0]?.message?.content?.trim() ||
      "No response generated by model.";

    return res.status(200).send(report);
  } catch (err) {
    console.error("💥 Server error:", err);
    return res.status(500).json({ error: "Server error" });
  }
}
