import fetch from "node-fetch";

export default async function handler(req, res) {
  // Allow only POST requests
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const inputs = req.body || {};

    // ----------------------------
    // 1️⃣  Build the system prompt
    // ----------------------------
    const systemPrompt = `
You are Pool ChemGPT, a professional pool-water technician.
Analyse the pool readings below and generate a clear treatment report.

${JSON.stringify(inputs, null, 2)}

Respond in markdown with:
- Heading: "Pool Water Treatment Report"
- Sections: Analysis, Chemical Adjustments (dosages in g/mL based on pool_volume), Step-by-Step Actions, Maintenance Checklist.
Keep the tone professional and concise.
`;

    // -------------------------------------------------------------
    // 2️⃣  Use the correct project-scoped OpenAI endpoint
    //     (works with sk-proj- keys)
    // -------------------------------------------------------------
    const apiUrl = `https://api.openai.com/v1/projects/${process.env.proj_64u39ono87YjrHAQVTAoCIQn}/chat/completions`;

    // ----------------------------
    // 3️⃣  Make the API request
    // ----------------------------
    const openaiRes = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.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}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: "Generate a pool chemical treatment report." },
        ],
        max_tokens: 800,
        temperature: 0.7,
      }),
    });

    const data = await openaiRes.json();

    // Log API output for debugging (viewable in Vercel → Deployments → Logs)
    console.log("🔍 OpenAI response:", JSON.stringify(data, null, 2));

    // ----------------------------
    // 4️⃣  Handle API errors
    // ----------------------------
    if (openaiRes.status !== 200) {
      return res
        .status(openaiRes.status)
        .json({ error: data.error?.message || "OpenAI API error" });
    }

    const report =
      data?.choices?.[0]?.message?.content?.trim() ||
      "No response generated by model.";

    return res.status(200).send(report);
  } catch (err) {
    console.error("💥 Server error:", err);
    return res.status(500).json({ error: "Server error" });
  }
}
